
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 74
#define YY_END_OF_BUFFER 75
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[184] =
    {   0,
       27,   27,    0,    0,    0,    0,    0,    0,    0,    0,
       75,   73,    1,    2,   46,   59,   38,   73,   28,   49,
       50,   36,   34,   55,   35,   73,   37,   24,   56,   43,
       45,   44,   58,   58,   53,   54,   73,   58,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       51,   73,   52,   31,   29,   30,   64,   60,   63,   64,
       68,   67,   68,   72,   71,   72,   42,   47,   32,   33,
       26,   27,   69,   65,    0,   24,   57,   57,   39,   41,
       40,   58,   58,    0,   27,   58,   58,   58,   58,   58,
       58,    5,   58,   58,   58,   58,    3,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   48,   61,   62,   66,
       70,   26,    0,   27,    0,   27,   27,   58,   58,   58,
       58,   58,   58,   58,   58,    4,   58,    6,   58,   58,
       58,   58,   58,   58,   58,   58,    0,   27,   25,   58,
       17,   14,   58,   58,   58,   11,   58,   19,   20,   58,
       58,   58,   58,   58,    8,   58,   25,   25,   13,   58,
       58,   58,    7,   58,   21,   58,   58,   58,   12,   25,
       58,   58,   15,   16,   22,    9,   58,   58,   10,   58,
       18,   23,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       24,   25,   26,    1,   27,    1,   28,   29,   30,   31,

       32,   33,   34,   35,   36,   22,   37,   38,   22,   39,
       40,   22,   22,   41,   42,   43,   44,   45,   46,   22,
       22,   22,   47,   48,   49,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    1,    1,    1,
        1,    6,    6,    1,    3,    1,    5,    7,    7,    6,
        6,    6,    7,    6,    6,    6,    6,    6,    7,    6,
        7,    6,    7,    6,    7,    6,    1,    1,    1
    } ;

static const flex_int16_t yy_base[194] =
    {   0,
        0,    0,   47,   48,   49,   54,   50,   55,   57,   58,
      214,  475,  475,  475,  189,  475,  475,  186,  475,  475,
      475,  475,  180,  475,  162,   47,   54,   61,  475,  147,
      135,  134,   46,   69,  475,  475,    0,   50,   65,   70,
       68,   71,   72,   86,   77,   91,   97,   99,  104,  110,
      475,   93,  475,  475,  475,  475,  475,  475,  475,  127,
      475,  475,  112,  475,  475,   91,  475,  475,  475,  475,
        0,  105,  475,  475,  118,  119,   86,  134,  475,  475,
      475,    0,  112,   73,   55,  130,  133,  135,  136,  139,
      141,  142,  153,  144,  155,  156,  158,  162,  164,  170,

      171,  173,  185,  177,  189,  190,  475,  475,  475,  475,
      475,    0,  206,  207,   54,  193,   49,  210,  212,  214,
      215,  218,  223,  216,  232,  230,  234,  236,  237,  239,
      245,  248,  250,  251,  253,  252,  280,  219,  281,  268,
      272,  283,  284,  285,  286,  287,  289,  290,  291,  292,
      298,  304,  309,  310,  311,  318,  331,  332,  325,  326,
      334,  337,  339,  340,  341,  343,  354,  357,  358,  361,
      360,  363,  365,  366,  371,  374,  378,  380,  382,  386,
      391,  394,  475,  421,  428,  435,  442,  446,  449,  451,
      457,  464,  467

    } ;

static const flex_int16_t yy_def[194] =
    {   0,
      183,    1,  184,  184,  185,  185,  186,  186,  187,  187,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  188,  183,  183,
      183,  183,  189,  189,  183,  183,  190,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  191,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      192,  183,  183,  183,  183,  188,  188,  188,  183,  183,
      183,  193,  189,  183,  193,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,

      189,  189,  189,  189,  189,  189,  183,  183,  183,  183,
      183,  192,  183,  183,  183,  188,  183,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  183,  183,  183,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  189,  183,  183,  189,  189,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  183,
      189,  189,  189,  189,  189,  189,  189,  189,  189,  189,
      189,  189,    0,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183

    } ;

static const flex_int16_t yy_nxt[525] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   12,   36,   37,   33,   38,   39,
       40,   41,   42,   43,   33,   44,   33,   45,   33,   33,
       46,   47,   33,   48,   49,   50,   51,   52,   53,   55,
       55,   58,   62,   59,   56,   56,   58,   62,   59,   65,
       65,   71,   82,   72,   73,  117,   82,   66,   66,   74,
      138,   85,   82,   60,   63,   75,   82,   76,   60,   63,
       84,   82,   84,   78,   82,   85,   82,   82,   82,  117,
       87,   82,   88,   82,   82,   82,   82,   82,   82,   89,

      183,   91,   82,   82,   90,   93,  111,   82,   94,   92,
       95,   96,   82,   82,  110,   82,   99,   82,   97,   71,
       82,   72,  100,   82,   98,   82,   82,  113,   82,  108,
       82,  101,   71,   75,  114,   76,   82,  104,   82,  102,
      107,   78,  103,  105,  106,  115,   82,  115,  183,   82,
      116,   82,   82,   81,   80,   82,   82,   82,   82,   82,
       82,   82,   82,  120,  118,   82,   79,   82,   82,   82,
       82,   82,   82,  122,   82,   70,  119,  121,   82,   82,
       82,   82,   82,  125,   82,  123,   82,   82,   82,   82,
       82,   69,   68,   82,  124,  126,   82,   82,  127,   82,

      132,   82,  129,   82,  128,   82,   82,  139,   67,  116,
      131,   82,  130,  183,  183,   82,   82,   84,  134,   84,
      133,   71,  117,  114,  135,  136,   82,  183,   82,  137,
       82,   82,   82,  139,   82,  138,   82,  140,   82,   82,
       82,   82,   82,  141,   82,  144,   82,  146,   82,   82,
       82,  145,   82,   82,  142,   82,   82,  143,   82,  147,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      149,   82,  183,  148,   82,  183,   82,   82,   82,   82,
      183,  183,  150,  155,   82,  151,  154,  183,   82,  156,
      152,  115,  153,  115,   82,  157,  138,  158,   82,   82,

       82,   82,   82,   82,  159,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,  160,
       82,  183,  183,  162,   82,   82,   82,   82,  161,  183,
       82,  163,  164,  183,   82,   82,   82,   82,  167,  166,
      165,   82,   82,  168,   82,  157,  157,  170,  158,  169,
       82,   82,   82,   82,  183,   82,   82,   82,  183,   82,
       82,  183,  183,   82,  171,   82,   82,   82,  173,   82,
       82,  172,  175,   82,   82,  157,   82,  170,  174,   82,
       82,   82,   82,   82,   82,  183,   82,   82,  176,   82,
       82,   82,   82,  183,   82,  177,   82,   82,   82,  183,

       82,  183,   82,  178,   82,  179,   82,   82,   82,  180,
       82,  181,   82,  183,  183,  183,  182,   82,  183,  183,
       82,   54,   54,   54,   54,   54,   54,   54,   57,   57,
       57,   57,   57,   57,   57,   61,   61,   61,   61,   61,
       61,   61,   64,   64,   64,   64,   64,   64,   64,   77,
       77,   77,   77,   83,   83,   83,   86,   86,  109,  109,
      183,  183,  183,  109,  112,  183,  112,  112,  112,  112,
      112,   82,   82,   82,   11,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183
    } ;

static const flex_int16_t yy_chk[525] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    5,    7,    5,    3,    4,    6,    8,    6,    9,
       10,   26,   33,   26,   27,  117,   38,    9,   10,   27,
      115,   85,   33,    5,    7,   28,   38,   28,    6,    8,
       34,   39,   34,   28,   41,   34,   40,   42,   43,   84,
       38,   39,   39,   45,   41,   34,   40,   42,   43,   39,

       77,   40,   44,   45,   39,   41,   66,   46,   42,   40,
       42,   43,   44,   47,   63,   48,   45,   46,   44,   72,
       49,   72,   46,   47,   44,   48,   50,   72,   83,   60,
       49,   47,   75,   76,   75,   76,   50,   48,   83,   47,
       52,   76,   47,   49,   50,   78,   86,   78,   78,   87,
       78,   88,   89,   32,   31,   90,   86,   91,   92,   87,
       94,   88,   89,   89,   87,   90,   30,   91,   92,   93,
       94,   95,   96,   91,   97,   25,   88,   90,   98,   93,
       99,   95,   96,   94,   97,   92,  100,  101,   98,  102,
       99,   23,   18,  104,   93,   95,  100,  101,   96,  102,

      102,  103,   99,  104,   98,  105,  106,  116,   15,  116,
      101,  103,  100,   11,    0,  105,  106,  113,  104,  113,
      103,  114,  113,  114,  105,  106,  118,    0,  119,  114,
      120,  121,  124,  138,  122,  138,  118,  118,  119,  123,
      120,  121,  124,  119,  122,  122,  126,  124,  125,  123,
      127,  123,  128,  129,  120,  130,  126,  121,  125,  125,
      127,  131,  128,  129,  132,  130,  133,  134,  136,  135,
      129,  131,    0,  127,  132,    0,  133,  134,  136,  135,
        0,    0,  130,  135,  140,  131,  134,    0,  141,  136,
      132,  137,  133,  137,  140,  139,  137,  139,  141,  142,

      143,  144,  145,  146,  140,  147,  148,  149,  150,  142,
      143,  144,  145,  146,  151,  147,  148,  149,  150,  143,
      152,    0,    0,  145,  151,  153,  154,  155,  144,    0,
      152,  147,  150,    0,  156,  153,  154,  155,  153,  152,
      151,  159,  160,  154,  156,  157,  158,  157,  158,  156,
      161,  159,  160,  162,    0,  163,  164,  165,    0,  166,
      161,    0,    0,  162,  160,  163,  164,  165,  162,  166,
      167,  161,  166,  168,  169,  170,  171,  170,  164,  172,
      167,  173,  174,  168,  169,    0,  171,  175,  167,  172,
      176,  173,  174,    0,  177,  168,  178,  175,  179,    0,

      176,    0,  180,  171,  177,  172,  178,  181,  179,  177,
      182,  178,  180,    0,    0,    0,  180,  181,    0,    0,
      182,  184,  184,  184,  184,  184,  184,  184,  185,  185,
      185,  185,  185,  185,  185,  186,  186,  186,  186,  186,
      186,  186,  187,  187,  187,  187,  187,  187,  187,  188,
      188,  188,  188,  189,  189,  189,  190,  190,  191,  191,
        0,    0,    0,  191,  192,    0,  192,  192,  192,  192,
      192,  193,  193,  193,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,

      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  183,  183,  183
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"




#line 9 "main.l"

#include<stdio.h>
#include<string.h>
#include "../1.SymbolTable/2105128_SymbolTable.cpp"

FILE *f1;
SymbolTable* symboltable = new SymbolTable(7,&HashFunction::sdbmHash);
int line_count=1;
int initial_line;
int err_count=0;
string str1="",str2="";
string cmnt="";
pair<string,pair<int,int>> inserted;

bool print_char_constant(string ch,int line_count){
    if(ch == "'\\n'"){
        fprintf(f1,"<CONST_CHAR, \n> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \n>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\t'"){
        fprintf(f1,"<CONST_CHAR, \t> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \t>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\\\'"){
        fprintf(f1,"<CONST_CHAR, \\> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \\>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\''"){
        fprintf(f1,"<CONST_CHAR, \'> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \'>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\a'"){
        fprintf(f1,"<CONST_CHAR, \a> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \a>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\f'"){
        fprintf(f1,"<CONST_CHAR, \f> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \f>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\r'"){
        fprintf(f1,"<CONST_CHAR, \r> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \r>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\b'"){
        fprintf(f1,"<CONST_CHAR, \b> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \b>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\v'"){
        fprintf(f1,"<CONST_CHAR, \v> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \v>\n\n",line_count,ch.c_str());
    }
    else if(ch == "'\\0'"){
        fprintf(f1,"<CONST_CHAR, \0> ");
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, \0>\n\n",line_count,ch.c_str());
    }
    else if(ch[1] == '\\' && ch[3] == '\''){
        fprintf(f1,"CONST_CHAR, %c> ",ch[2]);
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, %c>\n\n",line_count,ch.c_str(),ch[2]);
    }
    else if((ch[0] == '\'') && (ch[2] =='\'')){
        fprintf(f1,"<CONST_CHAR, %c> ", ch[1]); 
        printf("Line no %d: Token <CONST_CHAR> Lexeme %s found --> <CONST_CHAR, %c>\n\n",line_count,ch.c_str(),ch[1]);
    }
    else{
        err_count++;
        printf("Error at line no %d: Multi character constant error %s\n\n\n",line_count,ch.c_str());
        return false;
    }
    return true;
}

void print_escape_sequence(char* ch,string& str){
    if(!strcmp(ch,"\\\"")){
        str=str+"\"";
    }
    else if(!strcmp(ch,"\\n")){
        str=str+"\n";
    }
    else if(!strcmp(ch,"'\\t'")){
        str=str+"\t";
    }
    else if(!strcmp(ch,"'\\\\'")){
        str=str+"\\";
    }
    else if(!strcmp(ch,"'\\''")){
        str=str+"\'";
    }
    else if(!strcmp(ch,"'\\a'")){
        str=str+"\a";
    }
    else if(!strcmp(ch,"'\\f'")){
        str=str+"\f";
    }
    else if(!strcmp(ch,"'\\r'")){
        str=str+"\n";
    }
    else if(!strcmp(ch,"'\\b'")){
        str=str+"\b";
    }
    else if(!strcmp(ch,"'\\v'")){
        str=str+"\v";
    }
    else if(!strcmp(ch,"'\\0'")){
        str=str+"\0";
    }
}

pair<string,pair<int,int>> print_float(char* ch,int line_count){
    // for (int i=0;ch[i]!='\0';i++){
    //     ch[i]=tolower((unsigned char)ch[i]);
    // }
    fprintf(f1,"<CONST_FLOAT, %s> ",ch);
    printf("Line no %d: Token <CONST_FLOAT> Lexeme %s found\n\n",line_count,ch);
    inserted = symboltable->insert(ch,"CONST_FLOAT","");
    return inserted;
}


#line 746 "lex.yy.c"
#line 747 "lex.yy.c"

#define INITIAL 0
#define Char_const 1
#define String 2
#define Single_line_comment 3
#define Multi_line_comment 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 134 "main.l"


#line 971 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 184 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 475 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 136 "main.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 137 "main.l"
{line_count++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 139 "main.l"
{
    fprintf(f1,"<%s> ","IF");
    printf("Line no %d: Token <IF> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 143 "main.l"
{
    fprintf(f1,"<%s> ","FOR");
    printf("Line no %d: Token <FOR> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 147 "main.l"
{
    fprintf(f1,"<%s> ","DO");
    printf("Line no %d: Token <DO> Lexeme %s found\n\n",line_count,yytext);  
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 151 "main.l"
{
    fprintf(f1,"<%s> ","INT");
    printf("Line no %d: Token <INT> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 155 "main.l"
{
    fprintf(f1,"<%s> ","FLOAT");
    printf("Line no %d: Token <FLOAT> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "main.l"
{
    fprintf(f1,"<%s> ","VOID");
    printf("Line no %d: Token <VOID> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 163 "main.l"
{
    fprintf(f1,"<%s> ","SWITCH");
    printf("Line no %d: Token <SWITCH> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 167 "main.l"
{
    fprintf(f1,"<%s> ","DEFAULT");
    printf("Line no %d: Token <DEFAULT> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 171 "main.l"
{
    fprintf(f1,"<%s> ","ELSE");
    printf("Line no %d: Token <ELSE> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 175 "main.l"
{
    fprintf(f1,"<%s> ","WHILE");
    printf("Line no %d: Token <WHILE> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 179 "main.l"
{
    fprintf(f1,"<%s> ","BREAK");
    printf("Line no %d: Token <BREAK> Lexeme %s found\n\n",line_count,yytext);
} 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 183 "main.l"
{
    fprintf(f1,"<%s> ","CHAR");
    printf("Line no %d: Token <CHAR> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 187 "main.l"
{
    fprintf(f1,"<%s> ","DOUBLE");
    printf("Line no %d: Token <DOUBLE> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 191 "main.l"
{
    fprintf(f1,"<%s> ","RETURN");
    printf("Line no %d: Token <RETURN> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "main.l"
{
    fprintf(f1,"<%s> ","CASE");
    printf("Line no %d: Token <CASE> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 199 "main.l"
{
    fprintf(f1,"<%s> ","CONTINUE");
    printf("Line no %d: Token <CONTINUE> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 203 "main.l"
{
    fprintf(f1,"<%s> ","GOTO");
    printf("Line no %d: Token <GOTO> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 207 "main.l"
{
    fprintf(f1,"<%s> ","LONG");
    printf("Line no %d: Token <LONG> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "main.l"
{
    fprintf(f1,"<%s> ","SHORT");
    printf("Line no %d: Token <SHORT> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 215 "main.l"
{
    fprintf(f1,"<%s> ","STATIC");
    printf("Line no %d: Token <STATIC> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "main.l"
{
    fprintf(f1,"<%s> ","UNSIGNED");
    printf("Line no %d: Token <UNSIGNED> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 225 "main.l"
{
    inserted = symboltable->insert(yytext,"CONST_INT","");
    printf("Line no %d: Token <CONST_INT> Lexeme %s found\n\n",line_count,yytext);
    if(inserted.second.first ==0 && inserted.second.second ==0) symboltable->print_all_scope_nonempty_indices();
    else printf("< %s : CONST_INT > already exists in ScopeTable# %s at position %d, %d\n\n",yytext,inserted.first.c_str(),inserted.second.first,inserted.second.second);
    fprintf(f1,"<%s, %s> ","CONST_INT",yytext);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 232 "main.l"
{
    err_count++;
    printf("Error at line no %d: Ill formed number %s\n\n\n",line_count,yytext);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 236 "main.l"
{
    err_count++;
    printf("Error at line no %d: Too many decimal points %s\n\n\n",line_count,yytext);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 241 "main.l"
{
    inserted = print_float(yytext,line_count);
    if(inserted.second.first == 0 && inserted.second.second == 0) symboltable->print_all_scope_nonempty_indices();
    else printf("< %s : CONST_FLOAT > already exists in ScopeTable# %s at position %d, %d\n\n",yytext,inserted.first.c_str(),inserted.second.first,inserted.second.second);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 246 "main.l"
{
    BEGIN Char_const;
    str1="";
    str1 = str1+"\'";
}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 251 "main.l"
{
    err_count++;
    printf("Error at line no %d: Unterminated character %s\n\n\n",line_count,str1.c_str());
    line_count++;
    BEGIN INITIAL;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 257 "main.l"
{
    if(str1 == "\'"){
        err_count++;
        str1 = str1+"\'";
        printf("\nError at line no %d: Empty character constant error %s\n\n\n",line_count,str1.c_str());
    }
    else if(str1 == "\'\\"){
        err_count++;
        str1 = str1+"\'";
        printf("Error at line no %d: Unterminated character %s\n\n",line_count,str1.c_str());
    }
    else{
        str1 = str1+"\'";
        bool temp = print_char_constant(str1,line_count);
        if(temp){
            inserted = symboltable->insert(str1,"CONST_CHAR","");
            if(inserted.second.first == 0 && inserted.second.second == 0) symboltable->print_all_scope_nonempty_indices();
            else printf("< %s : CONST_CHAR > already exists in ScopeTable# %s at position %d, %d\n\n",yytext,inserted.first.c_str(),inserted.second.first,inserted.second.second);
        }
    }
    BEGIN INITIAL;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 279 "main.l"
{
    str1 = str1+yytext;
}
	YY_BREAK
case 32:
#line 285 "main.l"
case 33:
YY_RULE_SETUP
#line 285 "main.l"
{
    fprintf(f1,"<INCOP, %s> ",yytext);
    printf("Line no %d: Token <INCOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 34:
#line 290 "main.l"
case 35:
YY_RULE_SETUP
#line 290 "main.l"
{
    fprintf(f1,"<ADDOP, %s> ",yytext);
    printf("Line no %d: Token <ADDOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 36:
#line 295 "main.l"
case 37:
#line 296 "main.l"
case 38:
YY_RULE_SETUP
#line 296 "main.l"
{
    fprintf(f1,"<MULOP, %s> ",yytext);
    printf("Line no %d: Token <MULOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 39:
#line 301 "main.l"
case 40:
#line 302 "main.l"
case 41:
#line 303 "main.l"
case 42:
YY_RULE_SETUP
#line 303 "main.l"
{
    fprintf(f1,"<RELOP, %s> ",yytext);
    printf("Line no %d: Token <RELOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 43:
#line 308 "main.l"
case 44:
YY_RULE_SETUP
#line 308 "main.l"
{
    fprintf(f1,"<RELOP, %s> ",yytext);
    printf("Line no %d: Token <RELOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 312 "main.l"
{
    fprintf(f1,"<ASSIGNOP, %s> ",yytext);
    printf("Line no %d: Token <ASSIGNOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 316 "main.l"
{
    fprintf(f1,"<NOT, %s> ",yytext);
    printf("Line no %d: Token <NOT> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 47:
#line 321 "main.l"
case 48:
YY_RULE_SETUP
#line 321 "main.l"
{
    fprintf(f1,"<LOGICOP, %s> ",yytext);
    printf("Line no %d: Token <LOGICOP> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 325 "main.l"
{
    fprintf(f1,"<LPAREN, %s> ",yytext);
    printf("Line no %d: Token <LPAREN> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 329 "main.l"
{
    fprintf(f1,"<RPAREN, %s> ",yytext);
    printf("Line no %d: Token <RPAREN> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 333 "main.l"
{
    symboltable->EnterScope();
    fprintf(f1,"<LCURL, %s> ",yytext);
    printf("Line no %d: Token <LCURL> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 338 "main.l"
{
    symboltable->ExitScope();
    fprintf(f1,"<RCURL, %s> ",yytext);
    printf("Line no %d: Token <RCURL> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 343 "main.l"
{
    fprintf(f1,"<LTHIRD, %s> ",yytext);
    printf("Line no %d: Token <LTHIRD> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 347 "main.l"
{
    fprintf(f1,"<RTHIRD, %s> ",yytext);
    printf("Line no %d: Token <RTHIRD> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 351 "main.l"
{
    fprintf(f1,"<COMMA, %s> ",yytext);
    printf("Line no %d: Token <COMMA> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 355 "main.l"
{
    fprintf(f1,"<SEMICOLON, %s> ",yytext);
    printf("Line no %d: Token <SEMICOLON> Lexeme %s found\n\n",line_count,yytext);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 361 "main.l"
{
    err_count++;
    printf("Error at line no %d: Invalid prefix on ID or invalid suffix on Number %s\n\n",line_count,yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 365 "main.l"
{
    inserted = symboltable->insert(yytext,"ID","");
    fprintf(f1,"<ID, %s> ",yytext);
    printf("Line no %d: Token <ID> Lexeme %s found\n\n",line_count,yytext);
    if(inserted.second.first == 0 && inserted.second.second == 0) symboltable->print_all_scope_nonempty_indices();
    else printf("< %s : ID > already exists in ScopeTable# %s at position %d, %d\n\n",yytext,inserted.first.c_str(),inserted.second.first,inserted.second.second);
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 374 "main.l"
{
    BEGIN String;
    initial_line = line_count;
    str1="";
    str2="";
    str1=str1+yytext;
}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 381 "main.l"
{
    err_count++;
    printf("Error at line no %d: Unterminated string %s\n\n",initial_line,str1.c_str());
    line_count++;
    str1="";
    str2="";
    BEGIN INITIAL;
}
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 389 "main.l"
{
    line_count++;
    str1=str1+yytext;  
    str2=str2+""; 
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 394 "main.l"
{
    str1=str1+yytext;
    print_escape_sequence(yytext,str2);
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 398 "main.l"
{
    str1=str1+yytext;
    fprintf(f1,"<STRING, %s> ",str2.c_str());
    printf("Line no %d: Token <STRING> Lexeme %s found --> <STRING, %s>\n\n",line_count,str1.c_str(),str2.c_str());
    BEGIN INITIAL;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 404 "main.l"
{
    str1=str1+yytext;
    str2=str2+yytext;    
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 410 "main.l"
{
    BEGIN Single_line_comment;
    cmnt = "";
    cmnt = cmnt+yytext;
}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 415 "main.l"
{
    line_count++;
    cmnt = cmnt+yytext;
}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 419 "main.l"
{
    printf("Line no %d: Token <COMMENT> Lexeme %s found\n\n",line_count,cmnt.c_str());
    line_count++;
    BEGIN INITIAL;
} 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 424 "main.l"
{
    cmnt = cmnt+yytext;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 428 "main.l"
{
    BEGIN Multi_line_comment;
    initial_line = line_count;
    cmnt = "";
    cmnt = cmnt+yytext;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 434 "main.l"
{
    printf("Line no %d: Token <COMMENT> Lexeme %s*/ found\n\n",line_count,cmnt.c_str());
    BEGIN INITIAL;
}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 438 "main.l"
{
    line_count++;
    cmnt = cmnt+yytext;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 442 "main.l"
{
    cmnt = cmnt+yytext;
}
	YY_BREAK
case YY_STATE_EOF(Multi_line_comment):
#line 445 "main.l"
{
    err_count++;
    printf("Error at line no %d: Unterminated comment %s\n\n",initial_line,cmnt.c_str());
    symboltable->print_all_scope_nonempty_indices();
    printf("Total lines: %d\n",line_count);
    printf("Total errors: %d\n",err_count);
    return 0;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(Char_const):
case YY_STATE_EOF(String):
case YY_STATE_EOF(Single_line_comment):
#line 455 "main.l"
{
    symboltable->print_all_scope_nonempty_indices();
    printf("Total lines: %d\n",line_count);
    printf("Total errors: %d\n",err_count);
    return 0;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 461 "main.l"
{
    err_count++;
    printf("Error at line no %d: Unrecognized character %s\n\n",line_count,yytext);
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 466 "main.l"
ECHO;
	YY_BREAK
#line 1628 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 184 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 184 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 183);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 466 "main.l"


int main(int argc, char **argv){
    freopen("output_log.txt", "w", stdout);
    f1 = fopen("output_token.txt","w");
    if (argc != 2) {
        printf("No input file provided");
        fprintf(f1,"No input file provided");
        return 1;
    }
    char* filename = argv[1];
    FILE *input_file = fopen(filename,"r");
    if(input_file == NULL){
        perror("Error opening input file");
        return 1;
    }

    yyin = input_file;
    yylex();
    fclose(yyin);
    fclose(f1);

    return 0;
}
